repositories:
 - name: argo
   url: https://argoproj.github.io/argo-helm

releases:
- name: core-components-argocd
  namespace: argocd
  chart: argo/argocd-apps
  version: 2.0.2
  values:
    - core-components.yaml
