apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

helmCharts:
- name: keda
  repo: https://kedacore.github.io/charts
  version: v2.17.1
  namespace: kustomize-keda
  valuesFile: ../base/values.yaml
  additionalValuesFiles: 
    - values.yaml