repositories:
 - name: kedacore
   url:  https://kedacore.github.io/charts

releases:
- name: base
  chart: ./base
- name: keda
  namespace: helmfile-keda
  chart: kedacore/keda
  values:
  - ./values.yaml