apiVersion: helm.fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: keda
helmCharts:
- chartArgs:
    name: keda
    repo: https://kedacore.github.io/charts
    version: v2.17.1
    releaseName: keda
  templateOptions:
    namespace: kpt-keda
